---
title: "CellTrek Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
library(data.table)
library(ggplot2)
library(CellTrek)
library(dplyr)
library(Seurat)
library(RColorBrewer)
```

```{r}
brain_st_cortex <- readRDS("data/brain_st_cortex.rds")
print(dim(brain_st_cortex))
brain_sc <- readRDS("data/brain_sc.rds")
print(dim(brain_sc))
## Rename the cells/spots with syntactically valid names
brain_st_cortex <- RenameCells(brain_st_cortex, new.names=make.names(Cells(brain_st_cortex)))
brain_sc <- RenameCells(brain_sc, new.names=make.names(Cells(brain_sc)))
```
```{r}
SpatialDimPlot(brain_st_cortex)
DimPlot(brain_sc, label = T, label.size = 4.5)
```

```{r}
coord_lists <- readRDS("data/coord_lists_topspot1.rds")
all_coords <- rbindlist(coord_lists, idcol="run")
all_coords_wide <- dcast(all_coords, id ~ run, drop=FALSE, value.var=c("coord_x", "coord_y"))

rowDistsMean <- function(tmprow) {
  tmpx <- tmprow[2:11]
  tmpy <- tmprow[12:21]
  return(mean(dist(t(rbind(tmpx, tmpy))), na.rm = TRUE))
}
rowDistsMedian <- function(tmprow) {
  tmpx <- tmprow[2:11]
  tmpy <- tmprow[12:21]
  return(median(dist(t(rbind(tmpx, tmpy))), na.rm = TRUE))
}
dists <- data.table(id=all_coords_wide$id, mean=apply(all_coords_wide, 1, rowDistsMean))
dists$median <- apply(all_coords_wide, 1, rowDistsMedian)
dists <- melt(dists, measure.var = c("mean", "median"), variable.name = "euclidean distance", value.name="value")
ggplot(dists, aes(x = `euclidean distance`, y = value))+
  geom_boxplot()+
  theme_minimal()
```
After cell charting, we can interactively visualize the CellTrek result using the code from celltrek_vis

```{r}
plot_celltrek <- function(coords){
  coords <- coords[!is.na(cell_type)]
  img_temp <- brain_st_cortex@images$anterior1@image
  scale_factor <- brain_st_cortex@images$anterior1@scale.factors$lowres
  pnt_colors <- colorRampPalette(brewer.pal(9, 
                "Set1"))(length(levels(coords$cell_type)))
  plotly::plot_ly(d = coords, 
                  x = ~coord_y * scale_factor, 
                  y = ~ dim(img_temp)[1] - coord_x * scale_factor, customdata = ~id, 
                  color = ~cell_type,
                  colors = pnt_colors,
                  type = "scatter", 
                  mode = "markers", 
                  marker = list(line = list(color = "rgb(1,1,1)", 
                  width = 0.5), size = 8, opacity = 0.8)) %>% 
    plotly::layout(xaxis = list(range = c(0, dim(img_temp)[2]), showgrid = FALSE, showline = FALSE), 
                   yaxis = list(range = c(0, dim(img_temp)[1]), showgrid = FALSE, showline = FALSE), 
                   images = list(source = plotly::raster2uri(as.raster(img_temp)),
                                 x = 0, y = 0, sizex = dim(img_temp)[2], 
                                 sizey = dim(img_temp)[1], xref = "x", yref = "y", 
                                 xanchor = "left", yanchor = "bottom", 
                                 layer = "below", sizing = "stretch")
                   )
}
```


```{r}
p1 <- plot_celltrek(as.data.table(coord_lists[[1]]))
p2 <- plot_celltrek(as.data.table(coord_lists[[2]]))
p3 <- plot_celltrek(as.data.table(coord_lists[[3]]))
p4 <- plot_celltrek(as.data.table(coord_lists[[4]]))
p5 <- plot_celltrek(as.data.table(coord_lists[[5]]))
p6 <- plot_celltrek(as.data.table(coord_lists[[6]]))
p7 <- plot_celltrek(as.data.table(coord_lists[[7]]))
p8 <- plot_celltrek(as.data.table(coord_lists[[8]]))
p9 <- plot_celltrek(as.data.table(coord_lists[[9]]))
```

```{r, fig.width=12, fig.height=12}
plotly::subplot(p1, p2, p3, p4, p5, p6, p7, p8, p9, nrows=3)
```



```{r}
top_20_var_cells <- data.table(dists[`euclidean distance` == 'median'][order(value, decreasing = T)][1:20, c("id", "value")])
top_20_var_cells$top <- factor(paste("top", c(1:20), sep="_"), levels = paste("top", c(1:20), sep="_"))

plot_celltrek_var <- function(coord) {
  tmp <- merge(as.data.table(coord)[id %in% top_20_var_cells$id], top_20_var_cells)
  img_temp <- brain_st_cortex@images$anterior1@image
  scale_factor <- brain_st_cortex@images$anterior1@scale.factors$lowres
  pnt_colors <- colorRampPalette(brewer.pal(12, "Set1"))(length(levels(tmp$top)))
  plotly::plot_ly(d = tmp, 
                  x = ~coord_y * scale_factor, 
                  y = ~ dim(img_temp)[1] - coord_x * scale_factor, 
                  customdata = ~id, 
                  color = ~top,
                  text = ~top,
                  textposition = 'bottom center',
                  textfont = list(color = '#fff000', size = 8),
                  colors = pnt_colors,
                  type = "scatter", 
                  mode = "markers+text", 
                  marker = list(line = list(color = "rgb(1,1,1)", 
                  width = 0.5
                  ), size = 8, opacity = 0.8)) %>% 
    plotly::layout(xaxis = list(range = c(0, dim(img_temp)[2]), showgrid = FALSE, showline = FALSE), 
                   yaxis = list(range = c(0, dim(img_temp)[1]), showgrid = FALSE, showline = FALSE), 
                   images = list(source = plotly::raster2uri(as.raster(img_temp)),
                                 x = 0, y = 0, sizex = dim(img_temp)[2], 
                                 sizey = dim(img_temp)[1], xref = "x", yref = "y", 
                                 xanchor = "left", yanchor = "bottom", 
                                 layer = "below", sizing = "stretch")
                   )
}

```


```{r}
p1 <- plot_celltrek_var(as.data.table(coord_lists[[1]]))
p2 <- plot_celltrek_var(as.data.table(coord_lists[[2]]))
p3 <- plot_celltrek_var(as.data.table(coord_lists[[3]]))
p4 <- plot_celltrek_var(as.data.table(coord_lists[[4]]))
p5 <- plot_celltrek_var(as.data.table(coord_lists[[5]]))
p6 <- plot_celltrek_var(as.data.table(coord_lists[[6]]))
p7 <- plot_celltrek_var(as.data.table(coord_lists[[7]]))
p8 <- plot_celltrek_var(as.data.table(coord_lists[[8]]))
p9 <- plot_celltrek_var(as.data.table(coord_lists[[9]]))
```


```{r, fig.width=12, fig.height=12}
plotly::subplot(p1, p2, p3, p4, p5, p6, p7, p8, p9, nrows=3)
```


